name: personal-chat-project

networks:
  app-network:
    driver: bridge

services:
  # Node.js Frontend Service
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
      args:
        MONGODB_URI: mongodb://db:27017/personal-chat
    networks:
      - app-network
    ports:
      - "3010:3000"
    depends_on:
      - db
      - ai
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://ai:8000
      - MONGODB_URI=mongodb://db:27017/personal-chat

  # Python FastAPI Backend Service  
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8010:8000"
    depends_on:
      - db
    environment:
      - PYTHON_ENV=production
      - DATABASE_URL=mongodb://db:27017/personal_chat

  # MongoDB Database Service
  db:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "27020:27017"
    volumes:
      - mongodb-data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
      # - MONGO_INITDB_DATABASE=personal_chat

volumes:
  mongodb-data: